const en = {
  about: "About",
  books: "Books",
  blog: "Blog",
  blogPosts: "The latest blog posts",
  contact: "Contact",
  contactMobile: "Contact",
  koripallopaikat: "Basketball",
  basketballCourts: "Basketball courts",
  projects: "Projects",
  study: "Study",
  timeline: "Timeline",
  old: "Old websites",
  oldMobile: "Old",
  uses: "Uses",
  lab: "LAB University of Applied Sciences",
  unihelsinki: "University of Helsinki",
  russianStudies: "Russian Language and Literature",
  unihelGraduated: "Graduated as a Master of Arts (300 ECTS)",
  computerScience: "Computer Science",
  labStudies: "On hold (190/240 ECTS)",
  coursesAndCertificates: "Courses & Certificates",
  courses: "Courses",
  certificates: "Certificates",
  menu: "Menu",
  usesText:
    "The following is a list of the tools, software and any other things that I use on a daily basis. This page was inspired by Wes Bos and his project - ",
  work: "Work",
  petProjects: "Pet projects",
  "old.title.1": "First version of my website from early 2019",
  "old.title.2": "The second iteration published in late 2019",
  "old.title.3": "React version that was live from 2020 to 2023",
  "contact.link.mastodon": "Mastodon logo icon - link to my Mastodon profile",
  "contact.link.mail": "Email icon - link to my email address",
  "contact.link.linkedin": "LinkedIn logo icon - link to my LinkedIn profile",
  other: "Other",
  hardware: "Hardware",
  software: "Software",
  total: "Total: ",
  gallery: "Gallery",
  statistics: "Statistics",
  homePage: "Home page",
  mastersThesis: "The Master's Thesis",
  transcript: "Transcript of Records",
  library: "(Helsinki University Library)",
  link: "Link",
  "identifierServices.public": "Identifier services - Public services",
  "identifierServices.admin": "Identifier services - Internal services",
  publisherPortal: "Publisher Portal - Coming in 2024",
  english: "English",
  finnish: "Finnish",
  russian: "Russian",
  "charts.title.years": "Year statistics",
  "charts.title.languages": "Language statistics",

  // Alt texts
  "alt.old.1": "Screenshot of the first version of my website from 2019",
  "alt.old.2":
    "Screenshot of the second iteration of my website from late 2019",
  "alt.old.3":
    "Screenshot of the third iteration of my website which was live from 2020 to 2023",
  "alt.languageSwitcher":
    "Language switcher icon - click to change the language of the website",
  "alt.en": "USA flag icon - click to change the language to English",
  "alt.fi": "Finland flag icon - click to change the language to Finnish",
  "alt.languageArrow":
    "Arrow icon pointing to the chosen language of the website",
  "alt.blogLogo": "The logo of my blog, named 'Create React App'",
  "alt.contact":
    "Picture of a man sitting in an office calling someone on his phone",
};

export default en;
