const en = {
  about: "About",
  books: "Books",
  blog: "Blog",
  blogPosts: "The latest blog posts",
  contact: "Contact",
  contactMobile: "Contact",
  koripallopaikat: "Basketball",
  basketballCourts: "Basketball courts",
  projects: "Projects",
  workandstudy: "Work and studies",
  studies: "Studies",
  timeline: "Timeline",
  old: "Old websites",
  oldMobile: "Old",
  uses: "Uses",
  lab: "LAB University of Applied Sciences",
  unihelsinki: "University of Helsinki",
  russianStudies: "Russian Language and Literature",
  unihelGraduated: "Graduated as a Master of Arts (300 ECTS)",
  computerScience: "Computer Science",
  labStudies: "On hold (190/240 ECTS)",
  coursesAndCertificates: "Courses & Certificates",
  courses: "Courses",
  certificates: "Certificates",
  menu: "Menu",
  usesText:
    "The following is a list of the tools, software and any other things that I use on a daily basis. This page was inspired by Wes Bos and his project - ",
  work: "Work",
  petProjects: "Pet projects",
  "old.title.1": "First version of my website from early 2019",
  "old.title.2": "The second iteration published in late 2019",
  "old.title.3": "React version that was live from 2020 to 2023",
  "contact.link.mastodon": "Mastodon logo icon - link to my Mastodon profile",
  "contact.link.mail": "Email icon - link to my email address",
  "contact.link.linkedin": "LinkedIn logo icon - link to my LinkedIn profile",
  other: "Other",
  hardware: "Hardware",
  software: "Software",
  total: "Total: ",
  gallery: "Gallery",
  statistics: "Statistics",
  homePage: "Home page",
  mastersThesis: "The Master's Thesis",
  transcript: "Transcript of Records",
  library: "Helsinki University Library",
  link: "Link",
  "identifierServices.public": "Identifier services - Public services",
  "identifierServices.admin": "Identifier services - Internal services",
  english: "English",
  finnish: "Finnish",
  russian: "Russian",
  fiction: "Fiction",
  "non-fiction": "Non-fiction",
  "charts.title.years": "Year statistics",
  "charts.title.language": "Language",
  "charts.title.category": "Category",
  "skiplink.mainContent": "Skip to main content",
  "skiplink.contactsLinks": "Skip to social media and contact links",
  nationalLibrary: "National Library of Finland",
  frontendDeveloper: "Frontend Developer",
  softwareDeveloper: "Software Developer",
  lastUpdated: "Last updated: ",
  now: "Now",

  // Page titles
  "title.home": "Home page",
  "title.about": "About me",
  "title.blog": "Blog",
  "title.books": "Books",
  "title.statistics": "Books statistics",
  "title.contact": "Contact me",
  "title.projects": "My latest projects",
  "title.workandstudy": "Work and studies",
  "title.old": "Old versions of my website",
  "title.uses": "The tools I use",
  "title.now": "Now",

  // Meta descriptions
  "description.home": "Welcome to my website",
  "description.about": "Information about me",
  "description.blog": "The latest blog posts",
  "description.books": "The books I have read lately",
  "description.statistics": "Statistics for the books I have read",
  "description.contact": "Contact me - Mastodon, email and LinkedIn",
  "description.projects": "My latest projects - both pet and work",
  "description.workandstudy": "Information about my studies and work",
  "description.old": "Old versions of my website",
  "description.uses": "The tools and software that I use",

  // Alt texts
  "alt.old.1": "Screenshot of the first version of my website from 2019",
  "alt.old.2":
    "Screenshot of the second iteration of my website from late 2019",
  "alt.old.3":
    "Screenshot of the third iteration of my website which was live from 2020 to 2023",
  "alt.languageSwitcher":
    "Language switcher icon - click to change the language of the website",
  "alt.en": "USA flag icon - click to change the language to English",
  "alt.fi": "Finland flag icon - click to change the language to Finnish",
  "alt.languageArrow":
    "Arrow icon pointing to the chosen language of the website",
  "alt.blogLogo": "The logo of my blog, named 'Create React App'",
  "alt.contact":
    "Picture of a man sitting in an office calling someone on his phone",
  "alt.arrow": "Arrow icon",
  "alt.toolbox": "Toolbox icon",
  "alt.theme": "Light and dark theme switcher - flashlight icon",
  "alt.externalLink": "External link icon",
  "alt.githubLogo": "GitHub logo icon",
  "alt.linkedinLogo": "LinkedIn logo icon",
  "alt.mastodonLogo": "Mastodon logo icon",
  "alt.koripallopaikat":
    "Basketball emoji icon - link to my basketball related website",
  "alt.githubChart": "Chart showing my GitHub contributions",
  "alt.blogPen": "Pen emoji icon - link to my blog",
  "alt.email": "Postbox emoji icon - link for sending me an email",
  "alt.workandstudy": "Student emoji icon",
  "alt.book": "Book emoji icon",
  "alt.floppy": "Floppy disk emoji icon",
  "alt.penAndPaper": "Pen and paper emoji icon",
  "alt.comet": "Comet emoji icon",
  "alt.fire": "Fire emoji icon",
  "alt.home": "Home emoji icon - link to the home page",
  "alt.questionMark":
    "Question mark emoji icon - placeholder for future content",
  "alt.previewIds": "Preview image of the identifier services public website",
  "alt.previewIdsa": "Preview image of the identifier services admin website",
  "alt.previewCra": "Preview image of my personal blog",
  "alt.previewBasketball": "Preview image of my basketball courts website",
  "alt.previewWishlist": "Preview image of my wishlist website",
  "alt.briefcase": "Briefcase emoji icon",
  "alt.qualitydesk": "QualityDesk logo",
  "alt.library": "National Library logo",
  "alt.construction": "Under construction emoji icon",
  "alt.calendar": "Calendar emoji icon",

  // Aria labels
  "aria.workandstudy": "Page with information about my work and studies",
  "aria.blog": "Page with links to my blog posts",
  "aria.uses": "Page with the list of tools and software that I use",
  "aria.books": "Page with the list of books that I have read lately",
  "aria.projects": "Page with the list of both my pet and work projects",
  "aria.about": "Page with some images and information about me",
  "aria.contact": "Page with links to my mastodon, email and LinkedIn",
  "aria.old": "Page with links to the old versions of my website",
  "aria.randomLink": "Link to a random page on my website",
  "aria.statistics.language": "Language statistics for boks read in",
  "aria.statistics.category": "Category statistics for books read in",
  "aria.statistics.books": "Statistics for books read in last 5 years",
  "aria.skiplinks": "Skip links",
};

export default en;
